### ISSUE TITLE
unused argument (warn = F) 라는 오류가...

### ISSUE THREAD

**Issue by THE-R2** [mrchypark/gomSubtitleData#1]
> source("./getData.R")
Loading required package: rvest
Loading required package: xml2
Error in dir.create("./data", warn = F) : unused argument (warn = F)
>

**Comment by mrchypark** [comment]
아 그렇군요, 눈코딩 했더니..

dir.create("./data",showWarnings=F) 옵션이 이름이 독특했군요
수정했습니다!
피드백 주셔서 정말 감사합니다!
